# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 05:14
from __future__ import unicode_literals

import clothing.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=clothing.models.get_image_upload_to_path)),
                ('binary_image', models.FileField(upload_to=clothing.models.get_binary_image_upload_to_path)),
                ('price', models.PositiveIntegerField()),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('exhibiter', models.CharField(blank=True, max_length=255)),
                ('delivery_days', models.CharField(blank=True, max_length=255)),
                ('delivery_service', models.CharField(blank=True, max_length=255)),
                ('delivery_source', models.CharField(blank=True, max_length=255)),
                ('rank', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField()),
                ('page_url', models.URLField()),
                ('details', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_item_related', to='clothing.Category')),
            ],
            options={
                'ordering': ['category'],
                'verbose_name_plural': 'shop items',
            },
        ),
    ]
