# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20160610_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['category'], 'verbose_name_plural': 'Shop Items'},
        ),
    ]
