# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20160610_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['category'], 'verbose_name_plural': 'shop items'},
        ),
    ]
