# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='own',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='own',
            new_name='owner',
        ),
    ]
