# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 10:16
from __future__ import unicode_literals

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models

import clothing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothing', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(
                    upload_to=clothing.models.get_image_upload_to_path)),
                ('has_bought', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                        related_name='wardrobe_useritem_related', to='clothing.Category')),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user items',
            },
        ),
    ]
