# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='title',
            field=models.CharField(default='No title', max_length=255),
        ),
    ]
