# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160624_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopper',
            new_name='Profile',
        ),
    ]
