# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-17 03:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_useritem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='last_access',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 17, 3, 28, 8, 880504, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
