# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-17 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_useritem_last_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='last_access',
        ),
    ]
