# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-25 00:36
from __future__ import unicode_literals

import clothing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_auto_20170124_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='useritem',
            name='image',
            field=models.ImageField(upload_to=clothing.models.get_image_upload_to_path),
        ),
    ]
